/************************************

  █████╗  ██╗  ██╗  ██████╗  ██╗ ██╗
 ██╔══██╗ ██║  ██║ ██╔═══██╗ ██║ ██║
 ███████║ ███████║ ██║   ██║ ██║ ██║
 ██╔══██║ ██╔══██║ ██║   ██║ ██║ ╚═╝
 ██║  ██║ ██║  ██║ ╚██████╔╝ ██║ ██╗
 ╚═╝  ╚═╝ ╚═╝  ╚═╝  ╚═════╝  ╚═╝ ╚═╝

 Framework-agnostic core of the ahoi JS bridge.
 Framework adapters (e.g. `@acheul/ahoi-js/solid`) build on this module.

 ************************************/

export type SphereId = number;

/**
 * Version of the wasm⇄JS bridge ABI. Must match `ahoi::js_bridge::ABI_VERSION`
 * on the Rust side; checked at storage construction when the wasm module
 * exports `abi_version`.
 */
export const AHOI_ABI_VERSION = 1;

/**
 * Extracts the variant name from a key value's type, assuming serde's default
 * externally-tagged representation (the format produced by serde-wasm-bindgen
 * / ts-rs / Tsify): unit variants are string literals, payload variants are
 * single-key objects.
 */
export type VariantOf<K> =
    K extends string ? K
    : K extends object ? Extract<keyof K, string>
    : never;

/**
 * Resolves a key's return type, converter-agnostically:
 * 1. keys carrying a `ret` brand (e.g. Tsain's `tsain(brand(ret = ..))`)
 *    resolve from the brand;
 * 2. otherwise the variant name is looked up in the `Rets` map generated by
 *    `#[derive(Rets)]`;
 * 3. otherwise `Fallback`.
 */
export type KeyRet<X, Rets, Fallback> =
    X extends { readonly ret: infer R } ? R
    : VariantOf<X> extends keyof Rets ? Rets[VariantOf<X>]
    : Fallback;

/**
 * Return type of a Hail key. Falls back to `unknown` — the value exists, it
 * is just untyped.
 */
export type HailRet<X, Rets = {}> = KeyRet<X, Rets, unknown>;

/**
 * Return type of a Tell key. Falls back to `undefined`: un-annotated Tell
 * variants return `JsValue::undefined()` from Rust.
 */
export type TellRet<X, Rets = {}> = KeyRet<X, Rets, undefined>;

/** The wasm exports the bridge drives (from `wasm_bindgen_enrol_sphere!` etc.). */
export interface Job<PierKey, HailKey> {
    _enrol_pier(p: SphereId | undefined, k: PierKey): SphereId;
    _enrol_hail<T>(p: SphereId, k: HailKey): [SphereId, T];
    _clear_sphere(id: SphereId): void;
    _write_hail<T>(id: SphereId, v: T): void;
    /** wasm `abi_version` export; when present it is checked at init. */
    _abi_version?: () => number;
}

export function checkAbi(abi_version: (() => number) | undefined): void {
    if (abi_version !== undefined) {
        const got = abi_version();
        if (got !== AHOI_ABI_VERSION) {
            throw new Error(
                `[ahoi] bridge ABI mismatch: the wasm module speaks ABI v${got}, ` +
                `but this JS bridge expects v${AHOI_ABI_VERSION}. ` +
                `Align the \`ahoi\` crate and npm package versions.`,
            );
        }
    }
}

// Hail Entry
interface HailEntry<T> {
    _key_str: string;
    _count: number;
    _accessor: () => T;
    // write to rust side
    _writer?: (_: T) => void;
    _setter: (_: T) => void;
}

export class AhoiStorage<PierKey, HailKey> {
    /// <id, hail-entry>
    private _hails: Map<
        SphereId,
        HailEntry<any>
    > = new Map();

    private _hail_keys: Map<string, SphereId> = new Map();

    /**
     * Constructing a storage fully wires it: the ABI is checked and the
     * storage is bound as the page's dispatch target (see [`bindBridge`]).
     */
    constructor(
        public _job: Job<PierKey, HailKey>,
        public _batch_update: <T>(fn: () => T) => T,
    ) {
        checkAbi(_job._abi_version);
        bindBridge(this);
    }

    _enrol_pier = (
        par_pier_id: SphereId | undefined,
        pier_key: PierKey,
        on_clean_up: <F extends () => any>(fn: F) => F,
    ): SphereId => {
        const sphere_id = this._job._enrol_pier(par_pier_id, pier_key);

        on_clean_up(() => {
            this._job._clear_sphere(sphere_id);
        });

        return sphere_id;
    }

    _enrol_hail = <T>(
        par_pier_id: SphereId,
        key: HailKey,
        hat: (_: T) => [() => T, (_: T) => void],
        on_clean_up: <F extends () => any>(fn: F) => F,
    ): [() => T, (_: T) => void] => {
        const [a, b] = this._help_enrol_hail(par_pier_id, key, hat, on_clean_up, true);
        return [a, b!]
    }

    _enrol_read_hail = <T>(
        par_pier_id: SphereId,
        key: HailKey,
        hat: (_: T) => [() => T, (_: T) => void],
        on_clean_up: <F extends () => any>(fn: F) => F,
    ): () => T => {
        const [a, _] = this._help_enrol_hail(par_pier_id, key, hat, on_clean_up, false);
        return a;
    }

    private _help_enrol_hail = <T>(
        par_pier_id: SphereId,
        key: HailKey,
        hat: (_: T) => [() => T, (_: T) => void],
        on_clean_up: <F extends () => any>(fn: F) => F,
        use_write: boolean,
    ): [() => T, ((_: T) => void) | undefined] => {
        let _key_str = JSON.stringify(key);
        let sphere_id = this._hail_keys.get(_key_str);
        let accessor!: (() => T);
        let writer: ((_: T) => void) | undefined;

        if (sphere_id != undefined) {
            // 1) When the hail is already registered:
            //
            let hail = this._hails.get(sphere_id)!;
            // * Increase count
            hail._count++;
            // * use current accessor & writer
            accessor = hail._accessor;
            writer = hail._writer;
        } else {
            // 2) When key is not enrolled:
            //
            let [sphere_id_, value] = this._job._enrol_hail<T>(par_pier_id, key);
            sphere_id = sphere_id_;

            const [_accessor, _setter] = hat(value);
            accessor = _accessor;

            if (use_write) {
                const _writer = (v: T) => {
                    this._job._write_hail<T>(sphere_id_, v);
                };
                writer = _writer;
            }

            // record to _hails
            this._hails.set(sphere_id, {
                _count: 1,
                _key_str,
                _accessor,
                _writer: writer,
                _setter,
            });

            // record to _keys
            this._hail_keys.set(_key_str, sphere_id);
        }

        // add CleanUp Logic
        on_clean_up(() => {
            this._release_hail(sphere_id);
        });

        return [accessor, writer];
    }

    private _release_hail(sphere_id: SphereId): void {
        const sphere = this._hails.get(sphere_id);
        if (!sphere) return;
        sphere._count--;
        if (sphere._count <= 0) {
            // delete from _hails & _keys
            this._hails.delete(sphere_id);
            this._hail_keys.delete(sphere._key_str);
            // cleare sphere
            this._job._clear_sphere(sphere_id);
        }
    }

    _update_hails(hails: (SphereId | any)[]): void {
        this._batch_update(() => {
            for (let i = 0; i < hails.length; i += 2) {
                const sphere_id = hails[i] as SphereId;
                const value = hails[i + 1] as any;
                this._hails.get(sphere_id)?._setter(value);
            }
        });
    }
}

/**
 * Installs the `__AHOI__` global the wasm side dispatches hails into
 * (`js_namespace = "__AHOI__"`) and binds `ahoi` as its target. Called by the
 * [`AhoiStorage`] constructor — not part of the public API.
 *
 * The sink is created once; binding again only swaps the storage behind it —
 * so re-running setup code (dev-server HMR, tests) must not throw. The swap
 * slot lives on the global (not in module scope) because HMR re-evaluates
 * modules: the old sink closure must still reach the newest storage.
 * One bridge per page: the last storage constructed wins.
 */
function bindBridge(ahoi: AhoiStorage<any, any>) {
    const global = globalThis as Record<string, any>;
    if (global.__AHOI__ === undefined) {
        const bridge = {
            _storage: undefined as AhoiStorage<any, any> | undefined,
            hail: (hails: (SphereId | any)[]) => bridge._storage?._update_hails(hails),
        };
        global.__AHOI__ = bridge;
    }
    global.__AHOI__._storage = ahoi;
}
