/* Auto-generated by ahoi (https://github.com/acheul/ahoi). Do not edit. */
/* eslint-disable */

import type { Fruit } from "../pkg/ahoi_wasm_tsify";

// # Rets of Hail
export type HailRets = {
  Count: number;
  Doubled: number;
  Items: number[];
  Item: number | undefined;
  LastFruit: Fruit | undefined;
};

// # Rets of Tell
export type TellRets = {
  Increase: number;
  PopItem: number | undefined;
  SetFruit: Fruit;
};

