[workspace]
resolver = "3"
members = [
    "packages/ahoi",
    "packages/ahoi-core",
    "packages/ahoi-stock-macro",
    "packages/ahoi-rets-macro",
    "playgrounds/ahoi-wasm-tsrs",
    "playgrounds/ahoi-wasm-tsify",
    "playgrounds/bench",
    "book/examples/rust"
, "playgrounds/ahoi-wasm-tsain-todo"]
exclude = []

[workspace.package]
version = "0.1.1"
edition = "2024"
authors = ["Acheul <seoul605.21@gmail.com>"]
license = "MIT"
repository = "https://github.com/acheul/ahoi"
description = "Reactive State Management from Rust to Js"
categories = ["wasm", "web-programming"]
keywords = ["wasm", "web", "reactive", "signals", "state"]
readme = "./README.md"

[workspace.dependencies]
ahoi= { path = "packages/ahoi", version = "0.1.1" }
ahoi-core = { path = "packages/ahoi-core", version = "0.1.1" }
ahoi-stock-macro = { path = "packages/ahoi-stock-macro", version = "0.1.1" }
ahoi-rets-macro = { path = "packages/ahoi-rets-macro", version = "0.1.1" }
