[package]
name = "ahoi-wasm"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ahoi = { workspace = true, features = ["serde-wasm-bindgen"] }
serde = { version = "1.0", features = ["derive"] }
ts-rs = { version = "10" }
serde-wasm-bindgen = { version = "0.6.5" }
wasm-bindgen = { version = "0.2" }
gloo-console = { version = "0.4.0" }
console_error_panic_hook = { version = "0.1" }
gloo-timers = { version = "0.4", features = ["futures"] }
