//! Writing the ret maps to a `.ts` file.
//!
//! Private: [`TsFile`] is the whole surface, and `ts` re-exports it. Host-only,
//! so nothing here is compiled into a wasm build.

use super::*;

use std::collections::BTreeSet;

/// TypeScript names that never need an import.
///
/// The first group is everything `#[derive(Rets)]` itself can emit. The rest
/// are ambient names common enough that mentioning them would be noise. The
/// list is a heuristic, not a specification: it only feeds
/// [`TsFile::unresolved`], which nothing acts on unless the caller chooses to,
/// so a name it does not know costs one line in a report and nothing else.
const AMBIENT: &[&str] = &[
    // emitted by the Rets macro
    "string",
    "number",
    "boolean",
    "undefined",
    "Map",
    // primitives and top/bottom types
    "null",
    "void",
    "any",
    "unknown",
    "never",
    "object",
    "bigint",
    "symbol",
    "true",
    "false",
    // type-level keywords
    "readonly",
    "keyof",
    "typeof",
    "infer",
    "extends",
    "in",
    "is",
    "as",
    "asserts",
    "satisfies",
    // standard library
    "Array",
    "ReadonlyArray",
    "Set",
    "ReadonlySet",
    "ReadonlyMap",
    "Record",
    "Partial",
    "Required",
    "Readonly",
    "Pick",
    "Omit",
    "Exclude",
    "Extract",
    "NonNullable",
    "Promise",
    "Date",
    "RegExp",
    "Error",
    "Function",
    "Uint8Array",
    "Uint16Array",
    "Uint32Array",
    "Int8Array",
    "Int16Array",
    "Int32Array",
    "Float32Array",
    "Float64Array",
    "BigInt64Array",
    "BigUint64Array",
    "ArrayBuffer",
    "DataView",
];

/// Collects [`TsDecl`] declarations and writes a single `.ts` file.
///
/// Typically driven from a `#[test] fn generate()` in the wasm crate:
///
/// ```rust, ignore
/// use ahoi::js_bridge::TsFile;
///
/// TsFile::new()
///     .import("Fruit", "./Fruit") // data types the maps reference
///     .with::<Hail>()
///     .with::<Tell>()
///     .export("./bindings/Rets.ts");
/// ```
///
/// # Types the maps reference
///
/// A ret map names your types, but ahoi cannot know where your exporter put
/// them, so each one needs an [`import`](Self::import) line. Forget one and the
/// generated file references a name nothing declares, which surfaces later as a
/// `tsc` error some distance from its cause.
///
/// [`unresolved`](Self::unresolved) lists such names. It is opt-in rather than
/// enforced: `#[ret(ts = "...")]` passes arbitrary TypeScript through, and
/// whether a name resolves depends on the tsconfig, ambient declarations, and
/// globals that ahoi cannot see. If your project has no such types, assert on it
/// and the generate test becomes the check:
///
/// ```rust, ignore
/// let file = TsFile::new().with::<Hail>().with::<Tell>();
/// assert!(file.unresolved().is_empty(), "missing imports: {:?}", file.unresolved());
/// file.export("./bindings/Rets.ts");
/// ```
#[derive(Default)]
pub struct TsFile {
    imports: Vec<(String, String)>,
    decls: Vec<String>,
}

impl TsFile {
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds `import type { names } from "from";` for data types the ret
    /// maps reference, wherever your exporter emitted them
    /// (e.g. `.import("Fruit", "./Fruit")` for a ts-rs binding).
    ///
    /// `names` may list several types: `.import("Fruit, Basket", "./types")`.
    pub fn import(mut self, names: &str, from: &str) -> Self {
        self.imports.push((names.to_string(), from.to_string()));
        self
    }

    pub fn with<T: TsDecl>(mut self) -> Self {
        self.decls.push(T::ts_decl());
        self
    }

    pub fn to_source(&self) -> String {
        let mut out = String::from(
            "/* Auto-generated by ahoi (https://github.com/acheul/ahoi). Do not edit. */\n\
             /* eslint-disable */\n\n",
        );
        if !self.imports.is_empty() {
            for (names, from) in &self.imports {
                out.push_str(&format!("import type {{ {names} }} from \"{from}\";\n"));
            }
            out.push('\n');
        }
        for decl in &self.decls {
            out.push_str(decl);
            out.push('\n');
        }
        out
    }

    /// Type names the ret maps reference that no [`import`](Self::import)
    /// declares and that are not built into TypeScript.
    ///
    /// Empty means the generated file stands on its own. A name listed here
    /// usually wants an `.import(..)`, but not always: globals and ambient
    /// declarations resolve without one, and ahoi cannot see those. Treat the
    /// result as a lead, and assert on it only if your project has no such
    /// types.
    ///
    /// Sorted and deduplicated.
    pub fn unresolved(&self) -> Vec<String> {
        let mut known: BTreeSet<String> = AMBIENT.iter().map(|s| s.to_string()).collect();
        for (names, _) in &self.imports {
            // `Foo as Bar` is referenced by its local alias.
            known.extend(split_names(names));
        }
        let mut referenced = BTreeSet::new();
        for decl in &self.decls {
            // A map can name another map in the same file.
            known.extend(declared_names(decl));
            referenced.extend(referenced_names(decl));
        }

        referenced
            .into_iter()
            .filter(|name| !known.contains(name))
            .collect()
    }

    /// Writes the collected declarations to `path`, creating parent
    /// directories as needed.
    ///
    /// Writes whatever it was given. If you want missing imports to fail the
    /// build, assert on [`unresolved`](Self::unresolved) before calling this.
    pub fn export(&self, path: impl AsRef<std::path::Path>) {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("Failed to create parent directories");
        }
        std::fs::write(path, self.to_source()).expect("Failed to write ahoi TypeScript file");
        println!(
            "cargo:warning=Exported ahoi TypeScript types to {}",
            path.display()
        );
    }
}

/// Splits a comma-separated import clause, keeping the local alias of
/// `Original as Alias`.
fn split_names(names: &str) -> impl Iterator<Item = String> + '_ {
    names.split(',').filter_map(|part| {
        let name = part.rsplit(" as ").next().unwrap_or(part).trim();
        (!name.is_empty()).then(|| name.to_string())
    })
}

/// The `Foo` in `export type Foo = {`.
fn declared_names(decl: &str) -> Vec<String> {
    decl.lines()
        .filter_map(|line| {
            let rest = line.trim_start().strip_prefix("export type ")?;
            let name = rest.split(['=', '<', ' ']).next()?.trim();
            (!name.is_empty()).then(|| name.to_string())
        })
        .collect()
}

/// Type names appearing on the value side of a ret map's entries.
///
/// Only the right of the first `:` is scanned, so variant names on the left
/// (which look exactly like type names) are never mistaken for references.
fn referenced_names(decl: &str) -> Vec<String> {
    let mut out = Vec::new();
    for line in decl.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("//") || trimmed.starts_with("export type") {
            continue;
        }
        let Some(colon) = line.find(':') else {
            continue;
        };
        scan_idents(&line[colon + 1..], &mut out);
    }
    out
}

/// Pulls identifiers out of a TypeScript type expression.
///
/// Skips string literals, so `#[ret(ts = "\"a\" | \"b\"")]` contributes
/// nothing, and skips member names, so `Foo.Bar` only asks for `Foo`.
fn scan_idents(source: &str, out: &mut Vec<String>) {
    let bytes = source.as_bytes();
    let mut i = 0;

    while i < bytes.len() {
        let c = bytes[i];

        if c == b'"' || c == b'\'' || c == b'`' {
            i += 1;
            while i < bytes.len() {
                if bytes[i] == b'\\' {
                    i += 2;
                    continue;
                }
                if bytes[i] == c {
                    i += 1;
                    break;
                }
                i += 1;
            }
            continue;
        }

        if c.is_ascii_alphabetic() || c == b'_' || c == b'$' {
            let start = i;
            while i < bytes.len() {
                let d = bytes[i];
                if d.is_ascii_alphanumeric() || d == b'_' || d == b'$' {
                    i += 1;
                } else {
                    break;
                }
            }
            let is_member = start > 0 && bytes[start - 1] == b'.';
            if !is_member {
                out.push(source[start..i].to_string());
            }
            continue;
        }

        i += 1;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn file(decl: &str) -> TsFile {
        TsFile {
            imports: Vec::new(),
            decls: vec![decl.to_string()],
        }
    }

    const DECL: &str = "// # Rets of Hail\n\
                        export type HailRets = {\n  \
                          Count: number;\n  \
                          Fruit: Fruit | undefined;\n  \
                          Basket: Map<string, Fruit>;\n\
                        };\n";

    #[test]
    fn builtins_need_no_import() {
        let f = file(
            "export type R = {\n  A: number;\n  B: string[];\n  C: Map<string, boolean>;\n};\n",
        );
        assert!(f.unresolved().is_empty());
    }

    #[test]
    fn missing_import_is_reported_once() {
        assert_eq!(file(DECL).unresolved(), vec!["Fruit".to_string()]);
    }

    #[test]
    fn import_resolves_it() {
        let f = TsFile {
            imports: vec![("Fruit".into(), "./Fruit".into())],
            ..file(DECL)
        };
        assert!(f.unresolved().is_empty());
    }

    #[test]
    fn one_import_can_list_several() {
        let f = TsFile {
            imports: vec![("Fruit, Basket".into(), "./types".into())],
            ..file("export type R = {\n  A: Fruit;\n  B: Basket;\n};\n")
        };
        assert!(f.unresolved().is_empty());
    }

    #[test]
    fn aliased_import_resolves_the_alias() {
        let f = TsFile {
            imports: vec![("Apple as Fruit".into(), "./Apple".into())],
            ..file("export type R = {\n  A: Fruit;\n};\n")
        };
        assert!(f.unresolved().is_empty());
    }

    #[test]
    fn variant_names_are_not_references() {
        // `Fruit` and `Basket` are keys here, not types.
        let f = file("export type R = {\n  Fruit: number;\n  Basket: string;\n};\n");
        assert!(f.unresolved().is_empty());
    }

    #[test]
    fn string_literal_types_contribute_nothing() {
        let f = file("export type R = {\n  A: \"red\" | \"green\";\n};\n");
        assert!(f.unresolved().is_empty());
    }

    #[test]
    fn only_the_root_of_a_qualified_name_is_needed() {
        let f = file("export type R = {\n  A: Ns.Inner;\n};\n");
        assert_eq!(f.unresolved(), vec!["Ns".to_string()]);
    }

    #[test]
    fn maps_can_reference_each_other() {
        let f = TsFile {
            imports: Vec::new(),
            decls: vec![
                "export type HailRets = {\n  A: number;\n};\n".into(),
                "export type TellRets = {\n  B: HailRets;\n};\n".into(),
            ],
        };
        assert!(f.unresolved().is_empty());
    }

    /// `unresolved` is a report, not a gate. A name ahoi cannot resolve may
    /// still be a global, so it must never stop the file being written.
    #[test]
    fn export_writes_the_file_even_when_a_name_is_unresolved() {
        let path = std::env::temp_dir().join("ahoi-ts-test").join("Rets.ts");
        let _ = std::fs::remove_file(&path);

        file(DECL).export(&path);

        let written = std::fs::read_to_string(&path).expect("export should have written the file");
        assert!(written.contains("Fruit | undefined"));
    }
}
