/* Auto-generated by ahoi (https://github.com/acheul/ahoi). Do not edit. */
/* eslint-disable */

// # Rets of Hail
export type HailRets = {
  Count: number;
  Doubled: number;
  Items: number[];
  Item: number | undefined;
  Parity: number;
  Label: string;
  LabelRuns: number;
  TenTimes: number | undefined;
  TenTimesLoading: boolean;
  TickerRunning: boolean;
  Watch0Runs: number;
  Watch1Runs: number;
};

// # Rets of Tell
export type TellRets = {
  Increase: number;
  PopItem: number | undefined;
};

