//! Ret-map file generation for the JS bridge.
//!
//! ahoi does not convert your types to TypeScript — pick any exporter (ts-rs,
//! Tsify, Tsain, hand-written `.d.ts`). ahoi only describes what key variants
//! *return*: `#[derive(Rets)]` renders a `{Enum}Rets` map, and this module
//! writes those maps to a file.
//!
//! - [`TsDecl`]: a TS declaration contributed to the generated file —
//!   implemented by `#[derive(Rets)]` for key enums.
//! - [`TsFile`]: collects declarations and writes a `.ts` file — typically
//!   from a `#[test] fn generate()` in the wasm crate.
//!
//! ```rust, ignore
//! // (typically inside `#[test] fn generate()` of the wasm crate)
//! use ahoi::ts::TsFile;
//!
//! TsFile::new()
//!     .import("Fruit", "./Fruit") // data types the maps reference
//!     .with::<Hail>()
//!     .with::<Tell>()
//!     .export("./bindings/Keys.ts");
//! ```

/// A TS declaration contributed to the generated file.
///
/// Implemented by `#[derive(Rets)]` for key enums; collected by [`TsFile`].
pub trait TsDecl {
    fn ts_decl() -> String;
}

/// Collects [`TsDecl`] declarations and writes a single `.ts` file.
#[derive(Default)]
pub struct TsFile {
    imports: Vec<String>,
    decls: Vec<String>,
}

impl TsFile {
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds `import type { names } from "from";` — for data types the ret
    /// maps reference, wherever your exporter emitted them
    /// (e.g. `.import("Fruit", "./Fruit")` for a ts-rs binding).
    pub fn import(mut self, names: &str, from: &str) -> Self {
        self.imports
            .push(format!("import type {{ {names} }} from \"{from}\";\n"));
        self
    }

    pub fn with<T: TsDecl>(mut self) -> Self {
        self.decls.push(T::ts_decl());
        self
    }

    pub fn to_source(&self) -> String {
        let mut out = String::from(
            "/* Auto-generated by ahoi (https://github.com/acheul/ahoi). Do not edit. */\n\
             /* eslint-disable */\n\n",
        );
        if !self.imports.is_empty() {
            for import in &self.imports {
                out.push_str(import);
            }
            out.push('\n');
        }
        for decl in &self.decls {
            out.push_str(decl);
            out.push('\n');
        }
        out
    }

    /// Writes the collected declarations to `path`, creating parent
    /// directories as needed.
    pub fn export(&self, path: impl AsRef<std::path::Path>) {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).expect("Failed to create parent directories");
        }
        std::fs::write(path, self.to_source()).expect("Failed to write TypeScript file");
        println!("cargo:warning=Exported ahoi TypeScript types to {}", path.display());
    }
}
