//! Snapshot tests for `#[derive(Rets)]` output.

use crate::Rets;
use crate::ts::{TsDecl, TsFile};

// referenced data types need NO derives — they render by identifier and are
// only asserted to exist
#[allow(dead_code)]
enum Fruit {
    Apple,
}

#[allow(dead_code)]
struct Wrapped<T> {
    inner: T,
}

#[derive(Rets)]
#[allow(dead_code)]
enum TsHail {
    #[ret(i32)]
    Count,
    #[ret(Option<i32>)]
    Item(usize),
    #[ret(Vec<(String, Fruit)>)]
    Fruits,
    #[ret(Vec<Option<bool>>)]
    Flags,
    #[ret(std::collections::HashMap<String, Fruit>)]
    FruitMap,
    #[ret(Wrapped<u8>)]
    Generic,
    #[ret(ts = "MyCustom")]
    Insert(usize, i32),
    // un-annotated variants are omitted from the map
    Plain {
        a: bool,
        b: Option<String>,
    },
}

#[test]
fn test_rets_map() {
    let decl = TsHail::ts_decl();
    let expected = r#"// # Rets of TsHail
export type TsHailRets = {
  Count: number;
  Item: number | undefined;
  Fruits: [string, Fruit][];
  Flags: (boolean | undefined)[];
  FruitMap: Map<string, Fruit>;
  Generic: Wrapped<number>;
  Insert: MyCustom;
};
"#;
    assert_eq!(decl, expected);
}

#[derive(Rets)]
#[allow(dead_code)]
enum TsEmpty {
    A,
    B(u8),
}

#[test]
fn test_rets_empty_map() {
    assert_eq!(
        TsEmpty::ts_decl(),
        "// # Rets of TsEmpty\nexport type TsEmptyRets = {\n};\n"
    );
}

#[test]
fn test_ts_file_with_import() {
    let src = TsFile::new()
        .import("Fruit", "./Fruit")
        .with::<TsEmpty>()
        .to_source();
    let expected = r#"/* Auto-generated by ahoi (https://github.com/acheul/ahoi). Do not edit. */
/* eslint-disable */

import type { Fruit } from "./Fruit";

// # Rets of TsEmpty
export type TsEmptyRets = {
};

"#;
    assert_eq!(src, expected);
}
