// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hail Key
 */
export type Hail = "Count" | "Items" | { "Item": number } | "ItemLength" | "Fruits" | { "Fruit": string } | "FruitsEven" | "CompInfo" | "AboutInfo" | "CountResourceValue";
