/* Auto-generated by ahoi (https://github.com/acheul/ahoi). Do not edit. */
/* eslint-disable */

import type { Fruit } from "./Fruit";

// # Rets of Hail
export type HailRets = {
  Count: number;
  Items: number[];
  Item: number | undefined;
  ItemLength: number;
  Fruits: [string, Fruit][];
  Fruit: Fruit | undefined;
  FruitsEven: boolean;
  CompInfo: string;
  AboutInfo: string;
  CountResourceValue: number | undefined;
};

// # Rets of Tell
export type TellRets = {
  IncreaseCount: number;
  PopItem: boolean;
  InsertFruit: boolean;
};

