/* Auto-generated by ahoi (https://github.com/acheul/ahoi). Do not edit. */
/* eslint-disable */

import type { Fruit } from "./Fruit";

// # Rets of Hail
export type HailRets = {
  Count: number;
  Doubled: number;
  Items: number[];
  Item: number | undefined;
  CountX10: number | undefined;
  LastFruit: Fruit | undefined;
  FruitCounts: Map<string, number>;
  PanelInfo: string;
};

// # Rets of Tell
export type TellRets = {
  Increase: number;
  PopItem: number | undefined;
  SetFruit: number;
};

