// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fruit } from "./Fruit";

/**
 * Tell
 */
export type Tell = "IncreaseCount" | { "InsertItem": [number, number] } | "PopItem" | { "InsertFruit": [string, Fruit] } | { "SetCompInfo": string } | { "SetAboutInfo": string } | { "AddCount": number } | { "CallAddCountAction": number } | "CancelAddCountAction" | "ExSpawnBatch";
