// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fruit } from "./Fruit";

export type Tell = "Increase" | { "PushItem": number } | "PopItem" | { "SetFruit": Fruit } | { "AddCount": number } | { "StartTicker": number } | "StopTicker" | "PanicDemo";
